.\"                                      Hey, EMACS: -*- nroff -*-
.TH MBROLA 1 "May 17, 2005"
.SH NAME
mbrola \- multilingual software speech synthesizer
.SH SYNOPSIS
.B mbrola
.RI [ options ] <voice_database> <pho_file>... <output_file>
.SH DESCRIPTION
.PP
\fBmbrola\fP is a  speech synthesizer  based  on the concatenation  of
diphones. It takes a list of phonemes as input, together with prosodic
information  (duration of phonemes  and a piecewise linear description
of  pitch), and produces  speech samples  on 16  bits (linear), at the
sampling frequency of the diphone database. 
.PP
It is therefore NOT a Text-To-Speech  (TTS) synthesizer, since it does
not accept raw text as input.  In  order to obtain  a full TTS system,
you need to use this synthesizer in combination with a text processing
system that produces phonetic and prosodic commands.
For instance, you may use package \fBfreephone\fP to obtain complete
English TTS.
.PP
A `\-' instead of pho_file or output_file means stdin or stdout.
Extension of output_file ( raw, au, wav, aiff ) tells the wanted audio format.
.SH OPTIONS
\fBmbrola\fP understands following command line options.
.TP
.B \-h
.br
Show summary of options.
.TP
.B \-i
.br
Display the database information if any.
.TP
.B \-e
.br
Ignore fatal errors on unknown diphone.
.TP
.B \-c comment_char
Set COMMENT char (escape sequence in pho files).
.TP
.B \-F flush_command
Set FLUSH command name.
.TP
.B \-v volume
Volume ratio. Float ratio applied to output samples.
.TP
.B \-f freq_ratio
Frequency ratio. Float ratio applied to pitch points.
.TP
.B \-t time_ratio
Time ratio. Float ratio applied to phone durations.
.TP
.B \-l voice_freq
Voice frequency. Target frequency for voice quality in Hz.
.TP
.B \-R rename_list
Phoneme rename list of the form: `a A b B ...'
.TP
.B \-C clone_list
Phoneme clone list of the form: `a A b B ...'
.TP
.B \-I file
Initialization file containing one command per line.
\fBCLONE\fP, \fBRENAME\fP, \fBVOICE\fP, \fBTIME\fP, \fBFREQ\fP, \fBVOLUME\fP, \fBFLUSH\fP, \fBCOMMENT\fP,
and \fBIGNORE\fP are available.
.SH SEE ALSO
.BR freephone (1),
.BR sox (1).
.br
See /usr/share/doc/mbrola/readme.txt.gz for more info.
.SH AUTHOR
.nh
mbrola was written by Dr Thierry Dutoit <dutoit@tcts.fpms.ac.be>
.PP
This manual page was written by Igor B. Poretsky <master@goga.energo.ru>,
for the Debian project (but may be used by others).
